import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {startPreview} from '../scripts/preview.mjs';
const server=await startPreview();
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const check=name=>console.log('PASS',name);
try {
 await page.goto(server.url);
 const registered=await page.evaluate(()=>window.__pixelWorldsPreview.getContributions().map(c=>({area:c.area,path:c.data?.path,id:c.id})));
 for(const path of ['/pixel-worlds','/pw-agents'])for(const area of ['routes','sidebar.nav'])assert.ok(registered.some(c=>c.area===area&&c.path===path),`${area} ${path}`);
 assert.ok(registered.some(c=>c.id==='agents-open'&&c.area==='commandPalette'));
 check('Both products have route, navigation and palette contributions');
 await page.getByRole('button',{name:'Browse realms',exact:true}).click();
 assert.equal(await page.evaluate(()=>window.__previewExternal),'https://github.com/cygnostik/pd-pixel-worlds/blob/main/realms/README.md');
 check('Browse realms uses captured native openExternal, not network navigation');
 const packageFiles=await Promise.all((await readdir(new URL('../realms/',import.meta.url))).filter(name=>name.endsWith('.pwrealm.json')).map(async name=>{const path=new URL(`../realms/${name}`,import.meta.url);return {path,manifest:JSON.parse(await readFile(path,'utf8'))};}));
 for(const id of ['pd-office-space','pd-kitten-cafe','pd-tng-bridge']){
  const file=packageFiles.find(f=>f.manifest.id===id);assert.ok(file,`Real starter package missing: ${id}`);
  const {path,manifest}=file;
  await page.locator('input[type=file]').setInputFiles(path.pathname);
  await page.waitForFunction(id=>document.querySelector('.pw')?.dataset.theme===`import:${id}`,id);

  assert.equal(await page.locator('.pw-world-tabs button[aria-pressed=true]').count(),1);
  assert.equal(await page.locator('.pw-world-tabs button[aria-pressed=true]').innerText(),manifest.title);
 }
 check('All three real realm packages import and immediately select');
 await page.reload();
 await page.waitForFunction(()=>document.querySelector('.pw')?.dataset.theme==='import:pd-tng-bridge');
 await page.waitForFunction(()=>document.querySelectorAll('.pw-world-tabs button').length===6);
 check('Imported library and selected theme persist across reload');
 const before=await page.locator('.pw-world-tabs button').count();
 await page.locator('input[type=file]').setInputFiles({name:'bad.pwrealm.json',mimeType:'application/json',buffer:Buffer.from('{"id":"invalid"}')});
 await page.getByRole('alert').filter({hasText:'Could not import realm'}).waitFor();
 assert.equal(await page.locator('.pw-world-tabs button').count(),before);
 assert.equal(await page.locator('.pw').getAttribute('data-theme'),'import:pd-tng-bridge');
 await page.locator('input[type=file]').setInputFiles(packageFiles.find(f=>f.manifest.id==='pd-tng-bridge').path.pathname);
 await page.getByRole('alert').filter({hasText:'Could not import realm'}).waitFor();
 assert.equal(await page.locator('.pw-world-tabs button').count(),before);
 check('Malformed and duplicate imports cannot replace the selected library');
 await page.getByRole('button',{name:'Remove selected realm',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.pw-world-tabs button').length===5);
 assert.ok(!(await page.locator('.pw').getAttribute('data-theme')).startsWith('import:'));
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.pw-world-tabs button').length===5);
 check('Explicit removal persists and selects a built-in fallback');
 const listeners=await page.evaluate(()=>window.__pixelWorldsPreview.host.listenerCount());
 await page.getByRole('button',{name:'PW Agents',exact:true}).click();
 await page.locator('.pw-agents').waitFor();
 assert.equal(await page.locator('.pw-inspector,.pw-roster,.pw-header').count(),0);
 assert.equal(await page.locator('canvas').count(),1);
 assert.equal(await page.evaluate(()=>window.__pixelWorldsPreview.host.listenerCount()),listeners);
 await page.getByRole('combobox',{name:'Agents theme'}).selectOption('import:pd-office-space');
 await page.getByRole('button',{name:'Pause animation',exact:true}).click();
 await page.evaluate(()=>{for(let i=0;i<27;i++)window.__pixelWorldsPreview.host.emit({type:'message.start',session_id:`agents-fixture-${i}`,profile:'default',connection_id:'local',payload:{}});});
 await page.waitForFunction(()=>document.querySelector('.pw-agents-status')?.textContent.includes('15 off-stage'));
 assert.match(await page.locator('.pw-agents-status').innerText(),/12 on stage · 15 off-stage/);
 await page.getByRole('button',{name:'Next',exact:true}).click();
 assert.match(await page.locator('.pw-agents-pagination').innerText(),/Page 2 of 3/);
 await page.getByRole('button',{name:'Next',exact:true}).click();
 assert.match(await page.locator('.pw-agents-status').innerText(),/3 on stage · 24 off-stage/);
 assert.equal(await page.getByRole('button',{name:'Next',exact:true}).isDisabled(),true);
 check('PW Agents is scene-only with the same live bridge and complete overflow paging');
 await page.getByRole('button',{name:'Demo',exact:true}).click();
 assert.match(await page.locator('.pw-agents-status').innerText(),/Demo · illustrative · 6 on stage · 0 off-stage/);
 await page.getByRole('button',{name:'Live',exact:true}).click();
 assert.match(await page.locator('.pw-agents-status').innerText(),/12 on stage · 15 off-stage/);
 await page.evaluate(()=>window.__pixelWorldsPreview.host.state.gateway.set('disconnected'));
 await page.waitForFunction(()=>document.querySelector('.pw-agents-status')?.textContent.includes('unverified'));
 assert.match(await page.locator('.pw-agents-status').innerText(),/not connected/);
 check('Demo is isolated and disconnected evidence remains disclosed');
 await page.getByRole('button',{name:'Return to Worlds',exact:true}).click();
 await page.getByRole('button',{name:'Display mode',exact:true}).waitFor();
 assert.equal(await page.locator('.pw').getAttribute('data-theme'),'import:pd-office-space');
 assert.equal(await page.getByRole('button',{name:'Resume animation',exact:true}).count(),1);
 assert.equal(await page.locator('.pw-agent').count(),12);
 assert.equal(await page.evaluate(()=>window.__pixelWorldsPreview.host.listenerCount()),listeners);
 check('Routes share preferences, imported realms and live state');
 // Clearing the shared selection must win over either route's stale local ID.
 await page.getByRole('button',{name:'The Next Generation',exact:true}).click();
 for(const route of ['/pixel-worlds','/pw-agents']){
  if(route==='/pw-agents'){await page.getByRole('button',{name:'PW Agents',exact:true}).click();await page.locator('.pw-agents').waitFor();}
  await page.locator('.pw-ship-summary').click();
  const crew=page.getByRole('combobox',{name:'Crew member',exact:true});
  const id=await crew.locator('option').nth(1).getAttribute('value');
  await crew.selectOption(id);assert.equal(await crew.inputValue(),id);
  await page.evaluate(()=>window.__pixelWorldsPreview.getContributions().find(c=>c.id==='world-page').render().props.ship.select(null,'live'));
  await page.waitForFunction(()=>document.querySelector('.pw-ship-crew select')?.value==='');
  assert.equal(await page.getByRole('button',{name:'Locate crew',exact:true}).isDisabled(),true);
  const styling=await page.evaluate(()=>{
   const standard=document.querySelector('.pw-agents-options button')||document.querySelector('.pw-toolbar button');
   const style=element=>{const s=getComputedStyle(element);return {font:s.fontSize,padding:s.padding,radius:s.borderRadius,height:element.getBoundingClientRect().height};};
   const panel=document.querySelector('.pw-ship');
   return {standard:style(standard),scene:style(panel.querySelector('button')),decoration:getComputedStyle(panel,'::before').content,roomWidth:panel.querySelector('button').getBoundingClientRect().width};
  });
  assert.deepEqual(styling.scene,styling.standard,'Scene buttons use the standard compact control styling');
  assert.equal(styling.decoration,'none');assert.ok(styling.roomWidth<160,'Room button does not stretch across the panel');
 }
 check('Both routes honor shared deselection and use standard compact, undecorated scene buttons');
 await page.getByRole('combobox',{name:'Agents theme'}).selectOption('import:pd-office-space');
 await page.evaluate(()=>window.__pixelWorldsPreview.unmount());
 await page.waitForFunction(()=>document.querySelectorAll('canvas').length===0);
 assert.equal(await page.evaluate(()=>window.__pixelWorldsPreview.host.listenerCount()),0);
 await page.evaluate(()=>window.__pixelWorldsPreview.mount('/pw-agents'));
 await page.locator('.pw-agents').waitFor();
 assert.equal(await page.evaluate(()=>window.__pixelWorldsPreview.host.listenerCount()),listeners);
 await page.waitForFunction(()=>document.querySelectorAll('.pw-agents select option').length===5);
 assert.deepEqual(errors,[]);
 check('Dispose/remount restores one bridge, persisted library and no browser errors');
} finally {await browser.close();await server.close();}
