import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {startPreview} from '../scripts/preview.mjs';
import {SHIP_ROOMS} from '../src/ship-layout.js';
const capacities=Object.fromEntries(Object.entries(SHIP_ROOMS).map(([id,room])=>[id,room.stations.length]));
const capacity=Object.values(capacities).reduce((a,b)=>a+b,0);
const server=await startPreview(),browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],checks=[];
const out=new URL('../evidence/tng-rc/integration/',import.meta.url);await mkdir(out,{recursive:true});
page.on('pageerror',e=>errors.push(e.message));
const pass=name=>{checks.push(name);console.log('PASS',name);};
const state=()=>page.evaluate(()=>window.__pixelWorldsPreview.getContributions().find(c=>c.id==='world-page').render().props.ship.getSnapshot());
const pixels=()=>page.locator('canvas').evaluate(c=>c.toDataURL());
const room=id=>page.locator('.pw-ship-rooms button').filter({hasText:({bridge:'Bridge',engineering:'Engineering'})[id]}).click();
const capture=async name=>page.locator('.pw-world-card').screenshot({path:new URL(`${name}.png`,out).pathname});
try{
 await page.addInitScript(()=>localStorage.setItem('pixel-worlds-preview:ship-settings-v1',JSON.stringify({room:'chief-office',night:false,energy:'normal'})));
 await page.goto(server.url);await page.getByRole('button',{name:'Explore themes',exact:true}).click();
 await page.getByRole('button',{name:'The Next Generation',exact:true}).click();
 await page.getByRole('button',{name:'Pause animation',exact:true}).click();
 const initial=await state();assert.equal(initial.populations.demo.total,6);assert.deepEqual(initial.populations.demo.counts,{bridge:4,engineering:2,transit:0,offstage:0});
 assert.equal(initial.room,'bridge');assert.equal(await page.locator('.pw-ship-rooms button').count(),2);
 for(const id of ['bridge','engineering']){await room(id);await capture(id);assert.equal((await state()).room,id);}
 const locations=(await state()).populations.demo.locations;assert.deepEqual(locations,initial.populations.demo.locations);pass('Room switching preserves one persistent six-person crew, distributed across two rooms; saved office preference falls back to Bridge');
 await page.locator('.pw-ship-summary').click();await page.getByRole('button',{name:'Quiet',exact:true}).click();
 const before=await pixels();await page.getByRole('button',{name:'Night shift',exact:true}).click();assert.notEqual(await pixels(),before);
 assert.equal(await page.getByRole('button',{name:'Red alert drill',exact:true}).count(),0);
 await page.getByRole('button',{name:'Pulse warp core',exact:true}).click();assert.equal((await state()).room,'engineering');await capture('engineering-night-pulse');
 assert.equal(await page.getByRole('button',{name:'Replicate tea',exact:true}).count(),0);
 assert.deepEqual(await page.getByRole('combobox',{name:'Move to room',exact:true}).locator('option').evaluateAll(options=>options.map(o=>o.value)),['bridge','engineering']);
 await page.getByRole('button',{name:'Clear effects',exact:true}).click();
 await page.getByRole('button',{name:'Night shift',exact:true}).click();
 const diagnosticBefore=await pixels();await page.getByRole('button',{name:'Diagnostic sweep',exact:true}).click();assert.notEqual(await pixels(),diagnosticBefore);
 await page.getByRole('button',{name:'Clear effects',exact:true}).click();pass('Night shift, core pulse and diagnostic respond visibly and reset; office and tea controls are absent');
 const crew=page.getByRole('combobox',{name:'Crew member',exact:true});const first=initial.populations.demo.locations[0].id;
 await crew.selectOption(first);assert.equal((await state()).selectedIds.demo,first);assert.equal((await state()).room,'bridge');
 await crew.selectOption('');assert.equal((await state()).selectedIds.demo,null);pass('Crew selection, locate and explicit deselection work without console errors');
 await crew.selectOption(first);await page.getByRole('button',{name:'Resume animation',exact:true}).click();
 await page.getByRole('button',{name:'Reduced motion',exact:true}).click();
 await page.getByRole('combobox',{name:'Move to room',exact:true}).selectOption('engineering');await page.getByRole('button',{name:'Move crew locally',exact:true}).click();
 assert.equal((await state()).populations.demo.locations.find(l=>l.id===first).room,'engineering');assert.equal((await state()).populations.demo.activeTripId,null);
 await page.getByRole('button',{name:'Locate crew',exact:true}).click();assert.equal((await state()).room,'engineering');pass('Reduced-motion local movement arrives immediately, preserves identity and frees reservations');
 await page.getByRole('button',{name:'Reduced motion',exact:true}).click();
 await page.getByRole('combobox',{name:'Move to room',exact:true}).selectOption('bridge');await page.getByRole('button',{name:'Move crew locally',exact:true}).click();
 await page.waitForFunction(id=>window.__pixelWorldsPreview.getContributions().find(c=>c.id==='world-page').render().props.ship.getSnapshot().populations.demo.locations.find(l=>l.id===id)?.phase==='walking-out',first);
 await page.getByRole('button',{name:'Pause animation',exact:true}).click();const paused=await pixels();const frozen=await state();await page.waitForTimeout(250);assert.equal(await pixels(),paused);assert.deepEqual((await state()).populations.demo.locations,frozen.populations.demo.locations);await capture('engineering-departure-paused');
 await page.getByRole('button',{name:'Resume animation',exact:true}).click();
 await page.waitForFunction(id=>window.__pixelWorldsPreview.getContributions().find(c=>c.id==='world-page').render().props.ship.getSnapshot().populations.demo.locations.find(l=>l.id===id)?.room==='transit',first,{timeout:30000});
 assert.match(await page.locator('.pw-ship-selected').innerText(),/In transit/);await room('bridge');
 await page.waitForFunction(id=>{const s=window.__pixelWorldsPreview.getContributions().find(c=>c.id==='world-page').render().props.ship.getSnapshot();return s.populations.demo.locations.find(l=>l.id===id)?.room==='bridge'&&s.populations.demo.activeTripId===null;},first,{timeout:30000});
 pass('Real RAF journey walks, pauses, crosses the lift, transits and arrives at a distinct bridge station');
 await page.getByRole('button',{name:'Pause animation',exact:true}).click();
 // Supply fixture events to the real adapter; they are not live user sessions.
 await page.getByRole('button',{name:'Live agents',exact:true}).click();
 await page.evaluate(()=>{for(let i=0;i<27;i++)window.__pixelWorldsPreview.host.emit({type:'message.start',session_id:`ship-fixture-${i}`,profile:'default',connection_id:'local',payload:{}});});
 await page.waitForFunction(()=>window.__pixelWorldsPreview.getContributions().find(c=>c.id==='world-page').render().props.ship.getSnapshot().populations.live.total===27);
 let live=(await state()).populations.live;assert.deepEqual(live.counts,{...capacities,transit:0,offstage:27-capacity});
 await page.getByRole('searchbox',{name:'Find an agent'}).fill('ship-fixture-26');assert.deepEqual((await state()).populations.live.locations,live.locations);await page.getByRole('searchbox',{name:'Find an agent'}).fill('');
 await room('engineering');await capture('engineering-eight-integrated');
 const off=live.locations.find(l=>l.room==='offstage').id;await crew.selectOption(off);assert.match(await page.locator('.pw-ship-selected').innerText(),/Off-stage/);
 pass(`27-agent fixture has ${capacity} authored ship stations plus ${27-capacity} truthful off-stage entries; roster filtering does not teleport anyone`);
 await page.evaluate(()=>{window.__pixelWorldsPreview.host.emit({type:'tool.complete',session_id:'ship-fixture-0',profile:'default',connection_id:'local',payload:{tool_id:'ship-attention',name:'terminal',result:{error:'Illustrative failure'}}});});
 await room('engineering');assert.ok(await page.locator('.pw-ship-population').getByText(/need attention elsewhere/).count());
 await page.getByRole('button',{name:'PW Agents',exact:true}).click();await page.locator('.pw-agents').waitFor();
 assert.equal((await state()).room,'engineering');assert.deepEqual((await state()).populations.live.counts,live.counts);assert.ok(await page.locator('.pw-ship').count());
 assert.equal(await page.locator('.pw-ship-rooms button').count(),2);
 await page.locator('.pw-ship-summary').click();assert.deepEqual(await page.getByRole('combobox',{name:'Move to room',exact:true}).locator('option').evaluateAll(options=>options.map(o=>o.value)),['bridge','engineering']);assert.equal(await page.getByRole('button',{name:'Replicate tea',exact:true}).count(),0);assert.equal(await page.getByRole('combobox',{name:'Crew member',exact:true}).inputValue(),off);pass('PW Agents shares rooms, selected crew, roster and off-room attention without another event bridge');
 for(const width of [1200,640,390]){
  await page.setViewportSize({width,height:800});await page.waitForTimeout(100);
  assert.ok(await page.evaluate(()=>{const p=document.querySelector('.pw');return document.documentElement.scrollWidth<=innerWidth&&p.scrollWidth<=p.clientWidth+1;}));
  const controls=await page.locator('.pw-agents-controls').boundingBox();assert.ok(controls.x>=0&&controls.x+controls.width<=width+1);
  assert.ok(controls.y+controls.height<=800,'Control surface stays scrollable inside the pane');
  await page.getByRole('button',{name:'Return to Worlds',exact:true}).scrollIntoViewIfNeeded();const exit=await page.getByRole('button',{name:'Return to Worlds',exact:true}).boundingBox();assert.ok(exit.y>=0&&exit.y+exit.height<=800);
  await page.screenshot({path:new URL(`daily-${width}.png`,out).pathname});
 }
 pass('Daily-room controls and complete crew selector fit 1200/640/390px; scene retains readable scrolling');
 await page.setViewportSize({width:1440,height:1050});await page.getByRole('button',{name:'Return to Worlds',exact:true}).click();
 await page.getByRole('button',{name:'Display mode',exact:true}).click();assert.equal(await page.locator('.pw-ship').count(),1);await room('engineering');await page.screenshot({path:new URL('display-engineering.png',out).pathname});await page.keyboard.press('Escape');
 assert.equal(await page.locator('.pw').getAttribute('data-display'),'false');pass('Display mode exposes ship rooms and keeps its Escape exit');
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Explore themes',exact:true}).click();
 assert.equal((await state()).populations.demo.total,6);assert.equal((await state()).populations.live.total,27);pass('OS reduced motion and demo/live switching remain isolated');
 assert.deepEqual(errors,[]);pass('No uncaught browser errors');
 await writeFile(new URL('results.json',out),JSON.stringify({boundary:'Actual registered plugin and Canvas2D renderer, fixture SDK/events; no installation or live backend work.',checks,errors},null,2));
}finally{await browser.close();await server.close();}
